In [8]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import collections
from collections import Counter
from itertools import combinations

In [2]:
data = pd.read_csv('movie_bd_v5.csv')
#data.sample(5)
data

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year
0,tt0369610,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,Colin Trevorrow,The park is open.,Twenty-two years after the events of Jurassic ...,124,Action|Adventure|Science Fiction|Thriller,Universal Studios|Amblin Entertainment|Legenda...,6/9/2015,6.5,2015
1,tt1392190,150000000,378436354,Mad Max: Fury Road,Tom Hardy|Charlize Theron|Hugh Keays-Byrne|Nic...,George Miller,What a Lovely Day.,An apocalyptic story set in the furthest reach...,120,Action|Adventure|Science Fiction|Thriller,Village Roadshow Pictures|Kennedy Miller Produ...,5/13/2015,7.1,2015
2,tt2908446,110000000,295238201,Insurgent,Shailene Woodley|Theo James|Kate Winslet|Ansel...,Robert Schwentke,One Choice Can Destroy You,Beatrice Prior must confront her inner demons ...,119,Adventure|Science Fiction|Thriller,Summit Entertainment|Mandeville Films|Red Wago...,3/18/2015,6.3,2015
3,tt2488496,200000000,2068178225,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,J.J. Abrams,Every generation has a story.,Thirty years after defeating the Galactic Empi...,136,Action|Adventure|Science Fiction|Fantasy,Lucasfilm|Truenorth Productions|Bad Robot,12/15/2015,7.5,2015
4,tt2820852,190000000,1506249360,Furious 7,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,James Wan,Vengeance Hits Home,Deckard Shaw seeks revenge against Dominic Tor...,137,Action|Crime|Thriller,Universal Pictures|Original Film|Media Rights ...,4/1/2015,7.3,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1884,tt0120903,75000000,157299717,X-Men,Patrick Stewart|Hugh Jackman|Ian McKellen|Hall...,Bryan Singer,Evolution Begins,"Two mutants, Rogue and Wolverine, come to a pr...",104,Adventure|Action|Science Fiction,Twentieth Century Fox Film Corporation|Donners...,7/13/2000,6.6,2000
1885,tt0192255,22000000,13555988,The Little Vampire,Richard E. Grant|Jonathan Lipnicki|Jim Carter|...,Uli Edel,"They're not just best friends, they're blood b...","Based on the popular books, the story tells of...",95,Horror|Family|Foreign,New Line Cinema,10/27/2000,6.4,2000
1886,tt0131704,76000000,35134820,The Adventures of Rocky & Bullwinkle,Rene Russo|Jason Alexander|Piper Perabo|Randy ...,Des McAnuff,This summer it's not the same old bull.,Rocky and Bullwinkle have been living off the ...,88,Adventure|Animation|Action|Comedy|Family,Universal Pictures|Capella International|KC Me...,6/30/2000,4.0,2000
1887,tt0162983,40000000,36037909,Hanging Up,Meg Ryan|Diane Keaton|Lisa Kudrow|Walter Matth...,Diane Keaton,Every family has a few hang-ups.,A trio of sisters bond over their ambivalence ...,94,Comedy|Drama,Laurence Mark Productions|Columbia Pictures Co...,2/16/2000,5.2,2000
1888,tt0163676,15000000,5217498,The In Crowd,Susan Ward|Lori Heuring|Matthew Settle|Nathan ...,Mary Lambert,What would you do to get in?,A mentally disturbed young woman takes a job a...,105,Thriller,Warner Bros. Pictures,7/19/2000,5.2,2000

In [40]:
data.describe()

,budget,revenue,runtime,vote_average,release_year,profit
count,1.889000e+03,1.889000e+03,1889.000000,1889.000000,1889.000000,1.889000e+03
mean,5.431083e+07,1.553653e+08,109.658549,6.140762,2007.860773,1.010545e+08
std,4.858721e+07,2.146698e+08,18.017041,0.764763,4.468841,1.830733e+08
min,5.000000e+06,2.033165e+06,63.000000,3.300000,2000.000000,-1.657101e+08
25%,2.000000e+07,3.456058e+07,97.000000,5.600000,2004.000000,5.000000e+06
50%,3.800000e+07,8.361541e+07,107.000000,6.100000,2008.000000,4.400041e+07
75%,7.200000e+07,1.782626e+08,120.000000,6.600000,2012.000000,1.201842e+08
max,3.800000e+08,2.781506e+09,214.000000,8.100000,2015.000000,2.544506e+09

# Предобработка

In [18]:
answers = {} # создадим словарь для ответов

# тут другие ваши предобработки колонок например:

data['profit'] = data['revenue'] - data['budget']

#the time given in the dataset is in string format.
#So we need to change this in datetime format
# ...

# 1. У какого фильма из списка самый большой бюджет?

Использовать варианты ответов в коде решения запрещено.    
Вы думаете и в жизни у вас будут варианты ответов?)

In [7]:
# тут пишем ваш код для решения данного вопроса:
data[data.budget == data.budget.max()].original_title

723    Pirates of the Caribbean: On Stranger Tides
Name: original_title, dtype: object

In [19]:
# в словарь вставляем номер вопроса и ваш ответ на него
# Пример: 
#answers['1'] = '2. Spider-Man 3 (tt0413300)'
# запишите свой вариант ответа
answers['1'] = 'Pirates of the Caribbean: On Stranger Tides'
# если ответили верно, можете добавить комментарий со значком "+"

ВАРИАНТ 2

In [0]:
# можно добавлять разные варианты решения

# 2. Какой из фильмов самый длительный (в минутах)?

In [3]:
data[data.runtime == data.runtime.max()].original_title

1157    Gods and Generals
Name: original_title, dtype: object

In [20]:
# думаю логику работы с этим словарем вы уже поняли, 
# по этому не буду больше его дублировать
answers['2'] = 'Gods and Generals'

# 3. Какой из фильмов самый короткий (в минутах)?

In [8]:
data[data.runtime == data.runtime.min()].original_title

768    Winnie the Pooh
Name: original_title, dtype: object

In [21]:
answers['3'] = 'Winnie the Pooh'

# 4. Какова средняя длительность фильмов?

In [22]:
answers['4'] = '110'

# 5. Каково медианное значение длительности фильмов?

In [23]:
answers['5'] = '107'

# 6. Какой самый прибыльный фильм?
#### Внимание! Здесь и далее под «прибылью» или «убытками» понимается разность между сборами и бюджетом фильма. (прибыль = сборы - бюджет) в нашем датасете это будет (profit = revenue - budget)

In [23]:
# лучше код получения столбца profit вынести в Предобработку что в начале
data[data.profit == data.profit.max()].original_title

239    Avatar
Name: original_title, dtype: object

In [24]:
answers['6'] = 'Avatar'

# 7. Какой фильм самый убыточный?

In [4]:
data[data.profit == data.profit.min()].original_title

1245    The Lone Ranger
Name: original_title, dtype: object

In [25]:
answers['7'] = 'The Lone Ranger'

# 8. У скольких фильмов из датасета объем сборов оказался выше бюджета?

In [28]:
len(data[data.profit > 0])

1478

In [26]:
answers['8'] = '1478'

# 9. Какой фильм оказался самым кассовым в 2008 году?

In [11]:
films_2008 = data[data.release_year == 2008]
films_2008[films_2008.revenue == films_2008.revenue.max()].original_title

599    The Dark Knight
Name: original_title, dtype: object

In [27]:
answers['9'] = 'The Dark Knight'

# 10. Самый убыточный фильм за период с 2012 по 2014 г. (включительно)?

In [19]:
films_2012_2014 = data[(data.release_year >= 2012) & (data.release_year <= 2014)]
films_2012_2014[films_2012_2014.profit == films_2012_2014.profit.min()].original_title

1245    The Lone Ranger
Name: original_title, dtype: object

In [28]:
answers['10'] = 'The Lone Ranger'

# 11. Какого жанра фильмов больше всего?

In [28]:
# эту задачу тоже можно решать разными подходами, попробуй реализовать разные варианты
# если будешь добавлять функцию - выноси ее в предобработку что в начале
list_genres = []
for genres in data.genres:
    for genre in genres.split('|'):
        list_genres.append(genre)
data_genres = pd.Series(list_genres)
data_genres.value_counts()

Drama              782
Comedy             683
Thriller           596
Action             582
Adventure          415
Crime              315
Romance            308
Family             260
Science Fiction    248
Fantasy            222
Horror             176
Mystery            168
Animation          139
Music               64
History             62
War                 58
Western             19
Documentary          8
Foreign              2
dtype: int64

In [29]:
answers['11'] = 'Drama'

ВАРИАНТ 2

# 12. Фильмы какого жанра чаще всего становятся прибыльными?

In [4]:
profit_films = data[data.profit > 0]
list_profit_genres = []
for genre in profit_films.genres:
    for i in genre.split('|'):
        list_profit_genres.append(i)
data_profit_genres = pd.Series(list_profit_genres) 
data_profit_genres.value_counts()

Drama              560
Comedy             551
Thriller           446
Action             444
Adventure          337
Romance            242
Crime              231
Family             226
Science Fiction    195
Fantasy            188
Horror             150
Animation          120
Mystery            119
Music               47
History             46
War                 41
Western             12
Documentary          7
dtype: int64

In [30]:
answers['12'] = 'Drama'

# 13. У какого режиссера самые большие суммарные кассовые сбооры?

In [4]:
import pandas as pd
data = pd.read_csv('movie_bd_v5.csv')
directors = pd.Series(0, set(data['director'].str.cat(sep='|').split('|')))
for director in directors.index:
    directors[director] = data[data.director.str.contains(director)].revenue.sum()
directors.sort_values(ascending=False).head(1)

Peter Jackson    6490593685
dtype: int64

In [31]:
answers['13'] = 'Peter Jackson'

# 14. Какой режисер снял больше всего фильмов в стиле Action?

In [12]:
action_films = data[data.genres.str.contains('Action')]

list_directors = []
for directors in action_films.director:
    for director in directors.split('|'):
        list_directors.append(director)
data_directors = pd.Series(list_directors)
data_directors.value_counts()

Robert Rodriguez      9
Michael Bay           7
Paul W.S. Anderson    7
Ridley Scott          6
Antoine Fuqua         6
                     ..
John A. Davis         1
Denis Villeneuve      1
John Luessenhop       1
Philip G. Atwell      1
Rod Lurie             1
Length: 364, dtype: int64

In [32]:
answers['14'] = 'Robert Rodriguez'

# 15. Фильмы с каким актером принесли самые высокие кассовые сборы в 2012 году?

In [30]:
films_2012 = data[data.release_year == 2012]
#display(films_2012)
actors = pd.Series(0, set(films_2012['cast'].str.cat(sep='|').split('|')))        
#data_actors
for actor in actors.index:
    actors[actor] = films_2012[films_2012.cast.str.contains(actor)].revenue.sum()
actors.sort_values(ascending = False)

Chris Hemsworth       2027450773
Denis Leary           1629460639
Anne Hathaway         1522851057
Chris Evans           1519557910
Scarlett Johansson    1519557910
                         ...
Paula Patton             3428048
Danny Huston             2106557
Sami Gayle               2106557
Nicolas Cage             2106557
Josh Lucas               2106557
Length: 466, dtype: int64

In [33]:
answers['15'] = 'Chris Hemsworth'

# 16. Какой актер снялся в большем количестве высокобюджетных фильмов?

In [35]:
high_budget_films = data[data.budget > data.budget.mean()]
#display(high_budget_films)
list_actors = []
for actors in high_budget_films.cast:
    for actor in actors.split('|'):
        list_actors.append(actor)
data_actors = pd.Series(list_actors)
data_actors.value_counts()

Matt Damon           18
Adam Sandler         17
Angelina Jolie       16
Eddie Murphy         15
Samuel L. Jackson    15
                     ..
Jonathan Groff        1
Mr. T                 1
Eamonn Walker         1
Tony Goldwyn          1
Alex Borstein         1
Length: 1505, dtype: int64

In [34]:
answers['16'] = 'Matt Damon'

# 17. В фильмах какого жанра больше всего снимался Nicolas Cage?

In [30]:
films_Nicolas_Cage = data[data.cast.str.contains('Nicolas Cage')]
#display(films_Nicolas_Cage)
list_genres_Nicolas_Cage = []
for genres in films_Nicolas_Cage.genres:
    for genre in genres.split('|'):
        list_genres_Nicolas_Cage.append(genre)
data_genres_Nicolas_Cage = pd.Series(list_genres_Nicolas_Cage) 
data_genres_Nicolas_Cage.value_counts()

Action             17
Thriller           15
Drama              12
Crime              10
Fantasy             8
Adventure           7
Comedy              6
Science Fiction     4
Family              3
Animation           3
Mystery             3
History             2
Romance             1
War                 1
Horror              1
dtype: int64

In [35]:
answers['17'] = 'Action'

# 18. Самый убыточный фильм от Paramount Pictures

In [34]:
films_Paramount_Pictures = data[data.production_companies.str.contains('Paramount Pictures')]
#display(films_Paramount_Pictures)
films_Paramount_Pictures[films_Paramount_Pictures.profit == films_Paramount_Pictures.profit.min()].original_title

925    K-19: The Widowmaker
Name: original_title, dtype: object

In [36]:
answers['18'] = 'K-19: The Widowmaker'

# 19. Какой год стал самым успешным по суммарным кассовым сборам?

In [38]:
data_grouped_year = data.groupby(['release_year'])['revenue'].sum().sort_values(ascending = False)
display(data_grouped_year)

release_year
2015    25449202382
2014    23405862953
2013    23213799791
2012    23079001687
2011    22676791872
2010    21071204961
2009    20261791024
2008    18252781990
2007    18162406801
2004    15663430720
2005    15309425558
2006    14775042320
2003    14346123312
2002    14136361487
2001    13017764865
2000    10664099805
Name: revenue, dtype: int64

In [37]:
answers['19'] = '2015'

# 20. Какой самый прибыльный год для студии Warner Bros?

In [40]:
films_Warner_Bros = data[data.production_companies.str.contains('Warner Bros')]

data_grouped_year = films_Warner_Bros.groupby(['release_year'])['revenue'].sum().sort_values(ascending = False)
display(data_grouped_year)

release_year
2014    3243064519
2007    3183675217
2008    3050595031
2010    3008712985
2011    2845393682
2003    2745493377
2009    2737954136
2004    2731933725
2013    2599953400
2005    2412980298
2001    2266545668
2012    1869520056
2002    1702709901
2015    1691168351
2006    1521170743
2000    1025531386
Name: revenue, dtype: int64

In [38]:
answers['20'] = '2014'

# 21. В каком месяце за все годы суммарно вышло больше всего фильмов?

In [61]:
list_months = []
for months in data.release_date:
    list_months.append(months[:months.find('/')])
data_months = pd.Series(list_months)
data_months_sum = data_months.value_counts()
data_months_sum

9     227
12    190
10    186
8     161
3     156
4     149
6     147
11    146
7     142
5     140
2     135
1     110
dtype: int64

In [39]:
answers['21'] = 'Сентябрь'

# 22. Сколько суммарно вышло фильмов летом? (за июнь, июль, август)

In [62]:
data_months_sum[['6', '7', '8']].sum()

450

In [40]:
answers['22'] = '450'

# 23. Для какого режиссера зима – самое продуктивное время года?

In [7]:
data['month'] = data['release_date'].apply(lambda d: d.split('/')[0])
films_winter = data[(data.month == '12') | (data.month == '1') | (data.month == '2')]

list_directors = []
for directors in films_winter.director:
    for director in directors.split('|'):
        list_directors.append(director)
data_directors = pd.Series(list_directors)
data_directors.value_counts()

Peter Jackson         7
Steven Soderbergh     6
Clint Eastwood        6
Shawn Levy            4
Adam Shankman         4
                     ..
Kevin Macdonald       1
Charles Stone III     1
Craig Brewer          1
Gavin O'Connor        1
Sam Taylor-Johnson    1
Length: 358, dtype: int64

In [41]:
answers['23'] = 'Peter Jackson'

# 24. Какая студия дает самые длинные названия своим фильмам по количеству символов?

In [23]:
data_production_companies = pd.Series(0, set(data['production_companies'].str.cat(sep='|').split('|')))

for company in data_production_companies.index:
    data_production_companies[company] = data[data.production_companies.str.contains(company)].original_title.str.len().mean()
data_production_companies.sort_values(ascending = False)

Four By Two Productions                                 83.0
Jim Henson Company, The                                 59.0
Dos Corazones                                           47.0
Polsky Films                                            46.0
Museum Canada Productions                               46.0
                                                        ...
Nouvelles Ã‰ditions de Films (NEF)                       NaN
Munich Film Partners & Company (MFP) MI2 Productions     NaN
British Broadcasting Corporation (BBC)                   NaN
Flower Films (II)                                        NaN
Sony Pictures Worldwide Acquisitions (SPWA)              NaN
Length: 1771, dtype: float64

In [42]:
answers['24'] = 'Four By Two Productions'

# 25. Описание фильмов какой студии в среднем самые длинные по количеству слов?

In [10]:
data_production_companies = pd.Series(0, set(data['production_companies'].str.cat(sep='|').split('|')))

for company in data_production_companies.index:
    data_production_companies[company] = data[data.production_companies.str.contains(company)].overview.str.split().str.len().mean()
data_production_companies.sort_values(ascending = False)

Midnight Picture Show                                  175.0
Room 9 Entertainment                                   161.0
98 MPH Productions                                     159.0
Heineken Branded Entertainment                         159.0
Brookwell-McNamara Entertainment                       156.0
                                                       ...
Initial Entertainment Group (IEG)                        NaN
British Broadcasting Corporation (BBC)                   NaN
Danmarks Radio (DR)                                      NaN
Munich Film Partners & Company (MFP) ROE Production      NaN
Home Box Office (HBO)                                    NaN
Length: 1771, dtype: float64

In [43]:
answers['25'] = 'Midnight Picture Show'

# 26. Какие фильмы входят в 1 процент лучших по рейтингу? 
по vote_average

In [27]:
sort_films = data[['vote_average', 'original_title']].sort_values(['vote_average'], ascending = False)
sort_films[:round(len(sort_films)*0.01)]

      vote_average                                 original_title
599            8.1                                The Dark Knight
118            8.0                                   Interstellar
125            8.0                             The Imitation Game
9              8.0                                     Inside Out
34             8.0                                           Room
1183           7.9                        The Wolf of Wall Street
128            7.9                                      Gone Girl
1191           7.9                               12 Years a Slave
119            7.9                        Guardians of the Galaxy
1081           7.9  The Lord of the Rings: The Return of the King
1800           7.9                                        Memento
370            7.9                                      Inception
872            7.9                                    The Pianist
138            7.9                       The Grand Budapest Hotel
1188           7.8                                            Her
28             7.8                                      Spotlight
124            7.8                                     Big Hero 6
177            7.8                         The Fault in Our Stars
863            7.8          The Lord of the Rings: The Two Towers

In [44]:
answers['26'] = 'Inside Out, The Dark Knight, 12 Years a Slave'

# 27. Какие актеры чаще всего снимаются в одном фильме вместе?

ВАРИАНТ 2

In [16]:
data['list_of_actors'] = list(data.cast.str.split('|'))

cast_combination = collections.Counter()
for i in data['list_of_actors']:
    for j in list(combinations(i, 2)):
        cast_combination[j]+=1
#cast_combination       
data_cast_combination = pd.Series(cast_combination)
data_cast_combination.sort_values(ascending = False)

Daniel Radcliffe  Emma Watson             8
                  Rupert Grint            8
Rupert Grint      Emma Watson             7
Johnny Depp       Helena Bonham Carter    6
Ben Stiller       Owen Wilson             6
                                         ..
Emma Stone        Josh Brolin             1
Ryan Gosling      Nick Nolte              1
                  Josh Brolin             1
Sean Penn         Nick Nolte              1
Chris Pratt       Bryce Dallas Howard     1
Length: 18121, dtype: int64

In [45]:
answers['27'] = 'Daniel Radcliffe & Rupert Grint'

# Submission

In [46]:
# в конце можно посмотреть свои ответы к каждому вопросу
answers

{'1': 'Pirates of the Caribbean: On Stranger Tides',
 '2': 'Gods and Generals',
 '3': 'Winnie the Pooh',
 '4': '110',
 '5': '107',
 '6': 'Avatar',
 '7': 'The Lone Ranger',
 '8': '1478',
 '9': 'The Dark Knight',
 '10': 'The Lone Ranger',
 '11': 'Drama',
 '12': 'Drama',
 '13': 'Peter Jackson',
 '14': 'Robert Rodriguez',
 '15': 'Chris Hemsworth',
 '16': 'Matt Damon',
 '17': 'Action',
 '18': 'K-19: The Widowmaker',
 '19': '2015',
 '20': '2014',
 '21': 'Сентябрь',
 '22': '450',
 '23': 'Peter Jackson',
 '24': 'Four By Two Productions',
 '25': 'Midnight Picture Show',
 '26': 'Inside Out, The Dark Knight, 12 Years a Slave',
 '27': 'Daniel Radcliffe & Rupert Grint'}

In [47]:
# и убедиться что ни чего не пропустил)
len(answers)

27